kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: resnet-test-retain-claim
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels:
      name: resnet-test-retain
  storageClassName: local-path
